name: Spectrome backend API

on:
  pull_request:
    branches:
      - develop
      - master

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Setup Redis
        uses: shogo82148/actions-setup-redis@v1
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 . --count --max-complexity=20 --max-line-length=90 --statistics
      - name: Lint with pylint
        run: |
          pip install pylint
          pylint `find . | grep '.*.py$'`
      - name: Unit testing
        run: |
          CONFIG=./default.ini python -m unittest test
